### ISSUE TITLE
Azure Support: Determine deployment process using standard Azure tooling

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/codeontap#40]
To get the codeontap team familiar with how Microsoft Azure and its tooling works we should deploy a basic solution using the native tooling of Azure. This will allow us to identify potential changes that might be required or tooling change decisions before we start integrating it into CodeOnTap 

This ticket is considered closed when we have 

- [x] A Virtual machine deployed 
- [x] The virtual machine is in an isolated private network 
- [x] The Network has public internet access 
- [x] The Network can be configured for outbound public access only 
- [x] I can log into the virtual machine and copy a file to it
- [x] The deployment of these resources uses a declarative approach

**Comment by RossMurr4y** [comment]
@roleyfoley @ml019 with the RBAC group "Storage Account Contributor" granted to the system-managed identity, copying a file from the machine to object storage works successfully without having to pass credentials. It does not however then allow you to view the stored file because of the permissions breakdown happens with this default role.

this may be sufficient, but in the event it isn't then I propose the following options:

1. Grant the managed identity additional roles
2. Grant a higher level of access (which isn't great practice)
3. Have the template declare the creation of a custom role type that does include the permissions we require for both copying and reading files, and then granting that to the managed identity.

3 is probably the better practice.

Thoughts?

**Comment by roleyfoley** [comment]
I'd go with 3. We will need to know how to work with the role based access control and manage the fine grain permissions. Read/list is used quite a lot by applications so It will be a requirement

**Comment by roleyfoley** [comment]
We now have a standard virutal machine deployment with supporting infrastructure deployed as function separated templates. ( Network, storage, compute, security )
