### ISSUE TITLE
Azure Support: Deploy prefconfigured templates to Azure

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/codeontap#41]
Following on from #40 once we have a set of declarative, repeatable templates available we should be able to deploy these templates using CodeOnTap. This will allow us to update deployment tooling to support Azure without having to go to far into templating Azure resources 

This story is complete when we have the following 

- [ ] The ability to deploy a declarative template to Azure using the CodeOnTap tooling
- [ ] A component which represents a template in CodeOnTap 
- [ ] A deployed set of templates based on the solution in #40
