### ISSUE TITLE
Azure Support: Docker image build and deployment

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/codeontap#43]
Following on from #42 now that we have base level infrastructure components we need to start adding support for application level components. This includes the build and artefact management process provided in the codeontap/gen3-automation service 

The initial support will focus on docker as the build format with others being added once the concept has been proven 

This epic is considered finished when: 
- [ ] We have built a docker image artefact and stored it to an Azure supported artefact registry 
- [ ] The docker container has been deployed to the environment established in #42  
- [ ] A new version of the docker container can be deployed to the same environment
